with-expecter: true
dir: "mocks"
filename: "mock_{{.InterfaceName}}.go"
mockname: "Mock{{.InterfaceName}}"
outpkg: "mocks"
packages:
  github.com/saphieron/gowatcher/executor:
    interfaces:
      CommandExecutor: